const DESIGN_STYLES = {
  MINIMALIST: "MINIMALIST",
  INDUSTRIAL: "INDUSTRIAL",
  SCANDINAVIAN: "SCANDINAVIAN",
  MODERN_LUXURY: "MODERN_LUXURY",
  TROPICAL: "TROPICAL",
  JAPANDI: "JAPANDI",
};

module.exports = DESIGN_STYLES;
